version: '3'

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: .
      target: development # only build the development stage of our image
    env_file:
    - .env
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules # for hot reloading
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    command: npm run start:dev

  db:
    container_name: db
    image: postgres:13.4-alpine
    restart: always
    env_file:
      .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}