version: '3'

services:
  web:
    container_name: web
    build:
      context: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/app
    restart: on-failure
    entrypoint: scripts/web-docker-entrypoint.sh
    command: yarn start:dev

  db:
    container_name: db
    image: postgres:13.4-alpine
    environment:
      # Login without password
      POSTGRES_HOST_AUTH_METHOD: "trust"
      # Auto-create test DB
      POSTGRES_DB: test
    restart: always
