input AddAddressInput {
  """E.g. leave on porch, call on delivery, security codes on entry, etc."""
  additionalNotes: String = ""

  """State, province or region"""
  administrativeArea: String!
  countryCode: String!

  """General instructions for delivery and/or pickup"""
  instructions: AddressInstructionScalar!

  """Street address line 1"""
  line1: String!

  """Street address line 2"""
  line2: String = ""

  """City or town"""
  locality: String!

  """Place or business name"""
  organisationName: String = ""
  postalCode: String!

  """Different address types for customers, workers and their businesses"""
  type: AddressTypeScalar!
}

type Address {
  """E.g. leave on porch, call on delivery, security codes on entry, etc."""
  additionalNotes: String!

  """State, province or region"""
  administrativeArea: String!
  countryCode: String!
  createdAt: DateTime!
  id: ID!

  """General instructions for delivery and/or pickup"""
  instructions: AddressInstructionScalar!

  """Street address line 1"""
  line1: String!

  """Street address line 2"""
  line2: String!

  """City or town"""
  locality: String!

  """Place or business name"""
  organisationName: String!
  postalCode: String!

  """Different address types for customers, workers and their businesses"""
  type: AddressTypeScalar!
  updatedAt: DateTime!
}

"""General instructions for delivery and/or pickup"""
scalar AddressInstructionScalar

"""Different address types for customers, workers and their businesses"""
scalar AddressTypeScalar

type AuthUserResponse {
  token: String!
  user: User!
}

type CredentialsTakenError implements ErrorResponse {
  message: String!
  providedEmail: String!
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

interface ErrorResponse {
  message: String!
}

type InputError {
  field: String!
  messages: [String!]!
}

type InvalidCredentialsError implements ErrorResponse {
  message: String!
  providedEmail: String!
}

type InvalidInputError implements ErrorResponse {
  errors: [InputError!]!
  message: String!
}

input LoginSocialInput {
  accessToken: String!
  provider: SocialProviderScalar!
}

union LoginSocialResult = AuthUserResponse | SocialNotRegisteredError

input LoginUserInput {
  email: String!
  password: String!
}

union LoginUserResult = AuthUserResponse | InvalidCredentialsError

type Mutation {
  addAddress(input: AddAddressInput!): Address!
  login(input: LoginUserInput!): [LoginUserResult!]!
  loginSocial(input: LoginSocialInput!): [LoginSocialResult!]!
  register(input: RegisterUserInput!): [RegisterUserResult!]!
  registerSocial(input: RegisterSocialInput!): [RegisterSocialResult!]!
  removeAddress(id: ID!): Address!
  removeCurrentUser: User!
}

type Query {
  currentUser: User!
}

input RegisterSocialInput {
  accessToken: String!
  phoneCountryCode: String!
  phoneNumber: String!
  provider: SocialProviderScalar!
}

union RegisterSocialResult = AuthUserResponse | CredentialsTakenError | SocialAlreadyAssignedError

input RegisterUserInput {
  email: String!
  firstName: String!
  lastName: String!
  password: String!
  phoneCountryCode: String!
  phoneNumber: String!
}

union RegisterUserResult = AuthUserResponse | CredentialsTakenError | InvalidInputError

type SocialAlreadyAssignedError implements ErrorResponse {
  message: String!
  provider: SocialProviderScalar!
}

type SocialNotRegisteredError implements ErrorResponse {
  message: String!
  provider: SocialProviderScalar!
}

type SocialProvider {
  createdAt: DateTime!
  id: ID!
  provider: SocialProviderScalar!
  socialId: String!
  updatedAt: DateTime!
  user: User!
}

"""Social provider type such as facebook or google"""
scalar SocialProviderScalar

type User {
  addresses: [Address!]!
  createdAt: DateTime!
  email: String!
  firstName: String!
  id: ID!
  lastName: String!
  phoneCountryCode: String!
  phoneNumber: String!
  socialProviders: [SocialProvider!]!
  updatedAt: DateTime!
}
